# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'test-A4-王飞' do
  pod 'AFNetworking', '~> 3.1.0'
end

target 'test-A4-王飞Tests' do

end

target 'test-A4-王飞UITests' do

end

